(function ($, elementor) {
  "use strict"; var Induxo = {
    init: function () { var widgets = { 'induxo-slider.default': Induxo.Main_Banner_slider, 'induxo-testimonial.default': Induxo.Testimonial, 'history-slider.default': Induxo.History_Slider, 'induxo-project.default': Induxo.Project_gallery, 'induxo-project-slider.default': Induxo.Feature_project_slider, 'induxo-operate-locations.default': Induxo.Operate_location, 'induxo-annual-report.default': Induxo.Annual_report, }; $.each(widgets, function (widget, callback) { elementor.hooks.addAction('frontend/element_ready/' + widget, callback) }) }, Operate_location: function ($scope) { $('[data-toggle="tooltip"]').tooltip() }, Annual_report: function ($scope) { var $container = $scope.find('.graph-wrapper .graph'); var settings = null; var overlay_area = null; var graph_id = $container.attr('id'); settings = $container.data('settings'); Morris.Area({ element: graph_id, behaveLikeLine: JSON.parse(settings.overlay_area), lineColors: settings.label_colors, data: settings.graph_list, xkey: 'list_x', ykeys: ['list_y', 'list_z'], labels: settings.labels, resize: !0, }) }, Feature_project_slider: function ($scope) { var $container = $scope.find('.features-project'); var controls = JSON.parse($container.attr('data-controls')); var navShow = Boolean(controls.show_nav ? true : !1); var autoslide = Boolean(controls.auto_nav_slide ? true : !1); var project_slide_gap = parseInt(controls.project_slide_gap); if ($container.length > 0) { $container.owlCarousel({ loop: !0, autoplay: autoslide, autoplayHoverPause: !0, nav: navShow, margin: project_slide_gap, dots: !1, mouseDrag: !0, touchDrag: !0, smartSpeed: 900, navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>"], items: 4, responsive: { 0: { items: 1, }, 600: { items: 3, nav: navShow, }, 1000: { nav: navShow, } } }) } }, Project_gallery: function ($scope) {
      if ($('.grid').length > 0) {
        var $portfolioGrid = $('.grid'), colWidth = function () {
          var w = $portfolioGrid.width(), columnNum = 1, columnWidth = 0; if (w > 1200) { columnNum = 3 } else if (w > 900) { columnNum = 3 } else if (w > 600) { columnNum = 2 } else if (w > 450) { columnNum = 2 } else if (w > 385) { columnNum = 1 }
          columnWidth = Math.floor(w / columnNum); $portfolioGrid.find('.grid-item').each(function () { var $item = $(this), multiplier_w = $item.attr('class').match(/grid-item-w(\d)/), multiplier_h = $item.attr('class').match(/grid-item-h(\d)/), width = multiplier_w ? columnWidth * multiplier_w[1] : columnWidth, height = multiplier_h ? columnWidth * multiplier_h[1] * 0.4 - 12 : columnWidth * 0.3; $item.css({ width: width, }) }); return columnWidth
        }, isotope = function () { $portfolioGrid.isotope({ resizable: !0, itemSelector: '.grid-item', masonry: { columnWidth: colWidth(), gutterWidth: 3 } }) }; isotope(); $(window).resize(isotope)
      }
    }, Main_Banner_slider: function ($scope) { var $container = $scope.find('.hero-area'); var controls = JSON.parse($container.attr('data-controls')); var navShow = Boolean(controls.show_nav ? true : !1); var autoslide = Boolean(controls.auto_nav_slide ? true : !1); if ($container.length > 0) { $container.owlCarousel({ items: 1, loop: !0, autoplay: autoslide, nav: navShow, dots: !1, autoplayTimeout: 8000, autoplayHoverPause: !0, mouseDrag: !1, smartSpeed: 1100, navText: ['<i class="icon icon-left-arrow2">', '<i class="icon icon-right-arrow2">'], responsive: { 0: { items: 1, nav: !1, }, 600: { items: 1, nav: !1, }, 1000: { nav: navShow, } } }) } }, Testimonial: function ($scope) { var $container = $scope.find('.testimonial-carousel'); var show_nav = $scope.find('.testiomonial-area').data('nav'); if ($container.length > 0) { $container.owlCarousel({ items: 1, loop: !0, autoplay: !0, nav: show_nav, dots: !1, autoplayTimeout: 8000, autoplayHoverPause: !0, mouseDrag: !1, smartSpeed: 1100, navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>"], responsive: { 0: { nav: !1, }, 600: { nav: show_nav, }, 1000: { nav: show_nav, } } }) } }, History_Slider: function ($scope) { var $container = $scope.find('.ts-about-image-wrapper'); var navShow = !1; var autoslide = !1; if ($container.length > 0) { var controls = JSON.parse($container.attr('data-controls')); navShow = Boolean(controls.show_nav ? true : !1); autoslide = Boolean(controls.auto_nav_slide ? true : !1); $container.owlCarousel({ loop: !1, autoplay: autoslide, nav: navShow, margin: 5, dots: !1, mouseDrag: !0, touchDrag: !0, smartSpeed: 900, navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>"], items: 1, responsive: { 0: { items: 1, }, 600: { items: 1, }, 1000: { nav: navShow, } } }) } }
  }; $(window).on('elementor/frontend/init', Induxo.init)
}(jQuery, window.elementorFrontend))